# Generated by Django 5.1.7 on 2025-03-08 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SectorContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('expediente', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('vencimiento', models.DateField()),
                ('fecha_inicio_tramite', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('duracion_tramite', models.IntegerField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('estado_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.estadotramite')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.proveedor')),
                ('tipo_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipotramite')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.CharField(max_length=100)),
                ('monto_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='servicios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_ultima_orden_compra', models.CharField(max_length=100)),
                ('duracion_meses', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('saldo_dias', models.IntegerField()),
                ('nro_expediente_contratacion', models.CharField(max_length=100)),
                ('vigente', models.BooleanField(default=True)),
                ('en_tramite', models.BooleanField(default=False)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.estadocontratacion')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.sectorcontratacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
        ),
    ]
