# Generated by Django 5.1.7 on 2025-03-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_nombreservicio_alter_servicio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
