# Generated by Django 5.1.7 on 2025-03-08 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
