# Generated by Django 5.1.7 on 2025-03-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_alter_contratacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratacion',
            name='saldo_dias',
        ),
    ]
