# Generated by Django 5.1.7 on 2025-03-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_remove_contratacion_saldo_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='saldo_dias',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
