# Generated by Django 5.1.7 on 2025-03-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_contratacion_saldo_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacion',
            name='saldo_dias',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
