# Generated by Django 5.1.7 on 2025-03-09 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_alter_contratacion_saldo_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
