# Generated by Django 5.1.7 on 2025-03-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_contratacion_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='monto_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='nro_factura',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
