# Generated by Django 5.1.7 on 2025-03-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_add_facturas_to_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_set', to='servicios.servicio'),
        ),
    ]
