# Generated by Django 5.1.7 on 2025-03-09 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_alter_factura_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='facturas',
        ),
        migrations.AlterField(
            model_name='factura',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
    ]
