# Generated by Django 5.1.7 on 2025-03-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_remove_servicio_facturas_alter_factura_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='monto_unitario',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nro_factura',
        ),
        migrations.AlterField(
            model_name='contratacion',
            name='duracion_meses',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
